- README.md
- appveyor.yml
- community.yml
- roles/kitana/tasks/main.yml
https://github.com/pannal/Kitana
> Added kitana role

- roles/bookstack/tasks/main.yml
- settings.yml.sample
Adding customdomain feature same way as ombi does. So people can choose for wiki or bookstack or whatever they want.
> Bookstack: Add custom domain setting

- community.yml
- roles/invoiceninja/tasks/main.yml
- roles/invoiceninja/templates/invoiceninja_env.js2
- settings.yml.sample
> Invoice Ninja

- appveyor.yml
- community.yml
- roles/subsonic/tasks/main.yml
Added subsonic role files, edited appveyor.yml to include subsonic & edited community.yml to include.
> Subsonic Role

- roles/subsonic/tasks/main.yml
Changed the subsonic image used to one that provides a later version of Subsonic.
> Subsonic Image Change

- community.yml
- roles/guacamole/tasks/main.yml
> add guacamole role

- roles/jellyfin/tasks/main.yml
> restore port -502 error?

- roles/jellyfin/tasks/jellyfin_settings.yml
- roles/jellyfin/tasks/main.yml
remove some settings causing 502, remove published ports (again)
> add cache, media, data

- roles/radarr1080/tasks/main.yml
- roles/radarrx/tasks/template.yml
- roles/sonarr1080/tasks/main.yml
Updated the hotio images from the old hotio/suitarr:(son/rad)arr to the new hotio/(son/rad)arr
> updated hotio images

- appveyor.yml
- community.yml
- roles/wordpress/tasks/main.yml
- settings.yml.sample
Added wordpress container into community.
Uses official wordpress container, ties into cloudbox's own mariadb, automatically creates required database.
Install is bare install which allows user to browse to site and set up their own first user.
> Wordpress Addition

- roles/jellyfin/tasks/main.yml
Remove double devices - thanks l3udzz
> Copy paster error

- roles/myjdownloader/tasks/main.yml
myjdownloader/config/libs wasn't getting created for the 7zip stuff so the container wouldn't install. now it does. :)
> fixed jdownloader directory

- roles/booksonic/tasks/main.yml
- "/mnt:/mnt"
- "/mnt/unionfs/Media:/data"
> Add cloudbox standard paths

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/alltube/tasks/main.yml
Created a new role for alltube
-  Ability to use 2nd domain name if set in settings otherwise defaults to standard cloudbox domain name. 
- Downloads updated config.example.yml to /opt/alltube to help with additional configuration is user chooses.
alltube github: https://github.com/Rudloff/alltube
alltube docker: https://hub.docker.com/r/rudloff/alltube
> Created new role alltube

- roles/sonarrx/tasks/template.yml
The previous docker image was deprecated
> Update to main linuxserver.io sonarr container

- roles/logarr/tasks/main.yml
- roles/logarr/templates/config.json.j2
Update Logarr to alpha branch and add CB Logs
> Update Logarr to Alpha branch

- appveyor.yml
- community.yml
- roles/plex2/tasks/forced_quality_settings.yml
- roles/plex2/tasks/main.yml
- roles/plex2/tasks/p2_db_cache_size_settings.yml
- roles/subzero2/tasks/main.yml
- roles/webtools2/tasks/main.yml
> plex2 initial

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/synclounge/tasks/main.yml
Added synclounge
Server auto join is not working due to upstream issues
Address for server is: https://subdomain.domain.com/slserver
> added synclounge

- community.yml
Fix duplicate entries in community.yml
> Fix duplicate entries

- roles/radarrx/tasks/subtasks/darkerr.yml
- roles/radarrx/tasks/subtasks/suitarr_migration.yml
- roles/radarrx/tasks/template.yml
- roles/sonarrx/tasks/subtasks/darkerr.yml
- roles/sonarrx/tasks/subtasks/suitarr_migration.yml
- roles/sonarrx/tasks/template.yml
- Changed SonarrX to use Hotios images.
- Added darker subtasks to SonarrX & RadarrX.
- Added suitar migration to SonarrX & RadarrX.
- Changed restart policy to "unless-stopped" for SonarrX & RadarrX, inline with how Cloudbox deploys Sonarr/Radarr.
- Added suitarr_version variable check for SonarrX.
- Passthrough /dev/dri device to SonarrX & RadarrX if applicable.
>  SonarrX & RadarrX Edits 

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/asshama/tasks/main.yml
- roles/delugevpn/tasks/main.yml
- roles/epms/tasks/main.yml
- roles/unifi/tasks/main.yml
Absolute Series Scanner with HAMA for anime. Plex 
DelugeVPN Container.
Extended Personal Media Scanner. (Plex )
Unifi Controller.
> multi role

- defaults/settings.yml.default
- roles/bazarrx/tasks/main.yml
- roles/bazarrx/tasks/template.yml
- roles/deluge/tasks/main.yml
- roles/delugevpn/tasks/main.yml
- roles/radarrx/tasks/main.yml
- roles/radarrx/tasks/template.yml
- roles/sonarrx/tasks/main.yml
- roles/sonarrx/tasks/template.yml
- Added labels to all arrX containers, include check to stop & remove all containers with the label when running the role. This should resolve #95 
- Added setting to choose which version of deluge/delugevpn to deploy. V1 or V2.
> Resolve Issue With arrX. Include Deluge Version Choice

- appveyor.yml
- community.yml
- roles/handbrake/tasks/main.yml
Created a new role for handbrake WebUI. Easy to convert video from almost any format.
> Added HandBrake role

- roles/coder/tasks/main.yml
Changed coder default password to be the user.pass variable from Cloudbox
> Coder: Default Password Cloudbox

- appveyor.yml
- community.yml
- roles/pyload/tasks/main.yml
Fixed the errors from last time.
Default login: admin/pyload
Configure users via container console;
sudo -u abc -g abc /usr/bin/python /opt/pyload/pyLoadCore.py -u
follow prompts
> Added pyload role, properly

- README.md
- appveyor.yml
- community.yml
- roles/medusa/tasks/main.yml
Add medusa https://github.com/pymedusa/Medusa
> feature: Add medusa

- appveyor.yml
- community.yml
- roles/unmanic/tasks/main.yml
Add role to community.yml
Add role dir and main.yml
> unmanic: Initial Role Addition

- roles/coder/tasks/main.yml
Coder updated the internal docker port, reflecting that change here.
> Coder: Update Docker Port

- appveyor.yml
- community.yml
- roles/tdarr/tasks/main.yml
Add role to community.yml
Add role to appveyor.yml
Add role dir and main.yml
> Tdarr: Initial Role Addition

- appveyor.yml
- community.yml
- roles/rocketchat/tasks/main.yml
Basically translated the official docker-compose.yml into ansible and to work with cloudbox.
Added role dir and main.yml
Added role to community.yml
Added role to appveyor.yml
> RocketChat: Initial Role Addition

- roles/radarrx/tasks/subtasks/darkerr.yml
Figured no point changing task names given variables. 
Also I don't know what the fuck I'm doing...
Works for me, would appreciate someone testing it though.
> update radarrx to a new dark mode

- roles/tdarr/tasks/main.yml
Added nginx auth as tdarr does not have any inbuilt auth currently.
Amended some of the paths so that tdarr plugins ect are stored within /opt/tdarr/config
> Tdarr: Nginx Auth + Volume Changes

- roles/settings/tasks/main.yml
- roles/watchtower/tasks/main.yml
v2tec/watchtower deprecated in favor of containrrr/watchtower
> Watchtower: Update Docker image

- roles/deezloader-remix/tasks/main.yml
Include cloudflare-dns role, change "subdomain" to "record".
> Deezloader: Cloudflare Fixes

- appveyor.yml
- community.yml
- roles/ouroboros/tasks/main.yml
https://github.com/pyouroboros/ouroboros
> New role: Ouroboros

- roles/kitana/tasks/main.yml
The Kitana documentation states "/app/data" as the path that should be used.
> Fixed config path and docker image

- community.yml
- roles/gotify/tasks/main.yml
Adds Gotify server, a simple server for sending and receiving messages
Uses the original docker image (gotify/server) and docker environment variables to set initial user and pass.
> Gotify: New role

- README.md
> Wrong qbittorrent link.

- roles/logarr/templates/config.json.j2
Update default config to support NZBGet log rotation out of the box - backwards compatible to single NZBGet log file
> Logarr: Update config.json.j2

- roles/calibre-web/tasks/main.yml
Added missing quotes in option USE_CONFIG_DIR.
> calibre-web ansible update.

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/ombix/tasks/main.yml
- roles/ombix/tasks/template.yml
> Added new role: OmbiX

- roles/minecraft/tasks/main.yml
> Moved Data Directory and set defaults for whitelist and ops

- community.yml
- roles/requestrr/tasks/main.yml
Added new role for request application Requestrr. Also updated community.yml to add said role.
> New Role: Requestrr

- roles/coder/tasks/main.yml
See: https://github.com/cdr/code-server/issues/1428#issuecomment-600729221 & https://github.com/Cloudbox/Community/issues/213
> Coder: Remove allow-http flag (removed in code-server V3)

- roles/plex2/defaults/main.yml
https://github.com/nomego/Lazyman.bundle/commit/82f65782f025187e168524e88aacd1864844ef21
> Plex2: Update lookup for LazyMan

- README.md
- appveyor.yml
- community.yml
- roles/wallabag/tasks/main.yml
Only just started using this but seems to be a common request with other combination packages.
Using now to evaluate the stability - if others want to try it before merging, feel free.
> Wallabag - new role

- appveyor.yml
- community.yml
- roles/btrfsmaintenance/tasks/main.yml
- roles/jellyfin/tasks/main.yml
Create btrfsmaintenance role to install and activate btrfsmaintenance scripts from https://github.com/kdave/btrfsmaintenance
> New Role: btrfsmaintenance

- README.md
- appveyor.yml
- community.yml
- roles/emby2/files/dlna.xml
- roles/emby2/tasks/main.yml
- roles/emby2/tasks/subtasks/settings.yml
Added new role Emby2 for a secondary instance of Emby. 
1. Created New Role
2. Updated Appveyor.yml & Community.yml
3. Updated readme.md with new role
> New Role: Emby2 (Fixed)

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/requestrrx/tasks/main.yml
- roles/requestrrx/tasks/template.yml
Supplement on #217 Work done by @MBryde, just added the tag to community.yml 
Added a RequestrrX role in the same way SonarrX and RadarrX works. To easily deploy multiple instances of requestrr. Heavily lended code from other roles.
> New Role: RequestrrX

- README.md
- appveyor.yml
- community.yml
- roles/comicstreamer/tasks/main.yml
- roles/plex2/defaults/main.yml
Comicstreamer is a comics server (in the fashion of calibre for books)
> Add role comicstreamer

- README.md
- appveyor.yml
- community.yml
- roles/comixed/tasks/main.yml
Comixed is an actively developed comics server (in the fashion of calibre for books)
> Add role comixed

- README.md
- appveyor.yml
- community.yml
- roles/komga/tasks/main.yml
- roles/plex2/defaults/main.yml
Komga is an actively developed comics server (in the fashion of calibre for books)
> Add role komga

- README.md
- appveyor.yml
- community.yml
- roles/mylar3/tasks/main.yml
Recreated the pull request against develop. I hope I did this right...
> Add role: mylar3 (v3 for mylar)

- README.md
- appveyor.yml
- community.yml
- roles/plex2/defaults/main.yml
- roles/ubooquity/tasks/main.yml
Ubooquity is a comics server (in the fashion of calibre for books)
> Add role: ubooquity - comics server

- appveyor.yml
- community.yml
- roles/stash/tasks/main.yml
Verified working.  Using the Stash "development" branch at the direction of the app developers.
> Add new role for "Stash" 

- roles/tdarr/tasks/main.yml
Added support for Intel Quick Sync Video to the container so plugins using QSV can be used with the appropriate hardware.
> Tdarr QSV support

- README.md
- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/amongus/tasks/main.yml
Added a AmongUs Discord Bot role ([AmongUsAutoMute](https://github.com/denverquane/amongusdiscord))
> Added new role: amongus

- defaults/settings.yml.default
- roles/amongus/tasks/main.yml
> Bugfix Amongus patch

- appveyor.yml
- community.yml
- roles/apprise/tasks/main.yml
New role apprise based on https://hub.docker.com/r/caronc/apprise
> New role: apprise

- README.md
- appveyor.yml
- community.yml
- roles/mylar3/tasks/main.yml
- roles/ubooquity/tasks/main.yml
This role adds a the extendable [Red Discord](https://github.com/Cog-Creators/Red-DiscordBot) bot to your cloudbox setup as a docker container. It uses the `phasecorex/red-discordbot` image. The [Red Discord](https://github.com/Cog-Creators/Red-DiscordBot) bot is able to load different plugins or [cogs](https://cogboard.red/t/approved-repositories/210) to add functionality. There is no web panel with Red and can be managed entirely from your Discord server.
* Discord Server
* Cloudbox Setup with Community add-on (dev branch)
* A bot setup and it's token. Instructions for doing this can be found [here](https://discordpy.readthedocs.io/en/latest/discord.html)
1. Edit your `settings.yml` file and add your bot's token and the character you'd like to use as your command prefix. The command …
> Add a role for the Red Discord Bot

- appveyor.yml
- community.yml
- roles/deemix/tasks/main.yml
The last PR for this looked stale so I made this new one, it works on my server but I'm happy to make any necessary changes :+1:
> Add role: deemix

- roles/grafana/tasks/main.yml
Maybe a leftover from some old naming?
I honestly just copy-pasted from other roles and edited the name of the record from that.
I ran this onto my dedi and it worked, since I only copy-pasted this.
This is not a new role.
> Role wasn't creating record on Cloudflare

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/overseerr/tasks/main.yml
Added [Overseerr](https://github.com/sct/overseerr) a new Ombi-like request app for plex, radarr and sonarr
Ran install start to finish twice on my machine
> Add Overseerr role

- appveyor.yml
- community.yml
- roles/archivebox/tasks/main.yml
Added the role for [archivebox](https://github.com/ArchiveBox/ArchiveBox), the open-source self-hosted web archive. I ran the role on my own server and was able to use it correctly. 
Please let me know if any more changes are needed before it can be merged.
> Add role: ArchiveBox

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/qbittorrentvpn/tasks/main.yml
Creating as a draft - requires testing, please provide comments
I hope I have done everything correctly.
> New role: Qbittorrentvpn

- defaults/settings.yml.default
- roles/overseerr/tasks/main.yml
Added direct domain option to overserr
> Overseerr: Add direct domain option

- roles/transmissionx/tasks/main.yml
- roles/transmissionx/tasks/template.yml
Fixed my previous PR that had overlapping published ports with rutorrent from Cloudbox/Cloudbox
Tested on my system with 5 instances of transmission
> Changhed published port

- README.md
- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/alternatrr/tasks/main.yml
- roles/alternatrrx/tasks/main.yml
- roles/alternatrrx/tasks/template.yml
I added alternatrr. A tool for adding alternative titles to sonarr series with a simple webUI
I deployed it on my server. Both roles. Multiple times
> - Added alternatrr

- README.md
- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/vscode/tasks/main.yml
> add vscode role

- README.md
- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/conreq/tasks/main.yml
> added conreq role

- roles/filebot/tasks/main.yml
* fix: adding create htpasswd to filebot
* fix: fixing yml tabbing issue that cause ci to fail
> fix: adding create htpasswd to filebot (#342)

- README.md
- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/overseerrx/tasks/main.yml
- roles/overseerrx/tasks/template.yml
[Overseer](https://overseerr.dev/)
I use multiple oversseerr containers for multiple languages.
That's why I think it's useful to have this role.
> added overseerrx role

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/phantombot/tasks/main.yml
Added PhantomBot role.
PhantomBot is a Twitch chat bot powered by Java.
I was able to use it without issues, but I think further testing will be needed.
> New role: phantombot

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/plex-meta-manager/tasks/main.yml
Plex meta manager: https://github.com/meisnate12/Plex-Meta-Manager
> New role: Plex meta manager

- appveyor.yml
- community.yml
- roles/mkvtoolnix/tasks/main.yml
Adding MKVToolNix functionality allowing users to add/merge files into an .MKV file.
i.e. Adding a Subtitle file to an .MKV that was not previously included, or that has been updated.
Had an anime movie that had missing subs, but the release page included a separate subtitle file.
Added in the sub file and exported new file.
New file contains the subs.
- [✓] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [✓] I have updated the header in any files I may have used as templates with my own information
- [✓] I have added my new role to `appveyor.yml`
- [✓] I have added my new role to `community.yml`
- [✓] I have verified that any Docker images used are current and supported.
- [Pending?] I have made corresponding changes to the …
> Adding MKVToolNix functionality

- roles/plex-meta-manager/tasks/main.yml
Removed broken URL in PMM role
> PMM: Remove broken URL

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/xbackbone/tasks/main.yml
A lightweight file manager with full ShareX, Screencloud support and more
> New role: XBackbone

- appveyor.yml
- community.yml
- roles/prowlarr/tasks/main.yml
Added Prowlarr as a master compatible community role based using hotio's image with the "testing" tag.
> New Role: Prowlarr

- roles/mkvtoolnix/tasks/main.yml
Please review this template and edit it as appropriate.  It's not been provided as a thing to ignore.  If there are things that don't apply, remove them.  Don't just check boxes for the sake of checking boxes.  Remove this paragraph and the related thing below.
> mkvtoolnix: Add /mnt mount
