Cloudbox/Community

- roles/deluge/tasks/main.yml
"022 grants full access to the user deluged is running as and only read access to other accounts" .. not sure what 002 does
> Master -> Dev Sync

- roles/transmissionvpn/tasks/main.yml
TransmissionVPN cloudflare vars was set to "subdomain" but should've been set to "record".
> TransmissionVPN: Fix cloudflare vars error

- appveyor.yml
- roles/jellyfin/tasks/main.yml
Added lookup of current LazyMan IP address and addition to container's hosts file for the three domains used by LazyMan. See https://www.reddit.com/r/LazyMan/wiki/hostsfile for details. Based on previous code from Plex role.
LazyMan plugin for Jellyfin is available at https://github.com/crobibero/Jellyfin.Channels.LazyMan
Also fixed check of jellyfin_system_xml file in Settings Task.
> Add LazyMan IP addresses to hosts file

- defaults/settings.yml.default
- roles/settings/tasks/main.yml
- roles/unifi/tasks/main.yml
add override setting for unifi inform port to allow default 8080 to be used
unifi devices expect the inform port to be 8080 so this is easier to deploy, but still allows overriding if necessary.
I've left the 8089 as the in-file default as per the existing, but set the settings.yml.default to have 8080 as a default.
I've tested with a `sudo ansible-playbook community.yml --tags unifi` and the container was successfully started with 8080:8080 mapped.
> add override setting for unifi inform port 

- roles/transmissionvpn/tasks/main.yml
Added mounts for container's /data and /config so Docker does not automatically create Docker volumes on the main storage to host these
> TransmissionVPN: Slight changes to default_volumes

- roles/kitana/tasks/main.yml
Kitana doesn't realize its being run behind a reverse proxy so its
trying to request resources from non secure url's. This flag corrects
that behavior.
> Added -P flag to kitana role

- roles/ouroboros/tasks/main.yml
- roles/ouroboros/templates/ouroboros.env.j2
To allow for additional user configuration which remains persistent, the role will now import ouroboros.env into /opt/ouroboros/ouroboros.env and load that as an ENV file for the Docker container.
> Ouroboros: Change to env file configuration

- roles/wordpress/tasks/main.yml
The "latest" tag for wordpress is no longer based on alpine, passing through the UID and GID of the user only works with alpine. This was causing wordpress to fail to start, updated image to this alpine specific version, unfortunately unable to find a way to use "latest" but continue specifying which user to run as.
> Wordpress: Update Image

- roles/tdarr/tasks/main.yml
Tdarr: add environment variable to enable nvidia gpu transcoding when the appropriate hardware is available. Code borrowed from the Jellyfin role
> Tdarr: add environment variable to enable nvidia gpu transcoding

- roles/deezloader-remix/tasks/main.yml
Add /mnt so different file structures can be used if necessary.
> [deezloader-remix] Add /mnt to deezer image

- roles/embystat/tasks/main.yml
EmbyStat is really unstable with the nightly builds had an error with it such as 
``` 
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at EmbyStat.Web.Program.Main(String[] args) in d:\a\1\s\EmbyStat.Web\Program.cs:line 49
```
couldn't connect to the server pretty much just giving 
`502 Bad Gateway nginx/1.17.6 `
changing the tag to beta seem fixed the issue and it's more stable.
> EmbyStat: use beta tag

- roles/tdarr/tasks/main.yml
As per changes to the source container:
Change log
Beta v1.1091 release [24th May 2020]:
All containers are now the same (tdarr, tdarr_aio, tdarr_aio:qsv) and are based on the tdarr_aio:qsv container which supports NVENC and QSV hardware transcoding.
tdarr_aio and tdarr_aio:qsv users, you can continue using those containers as normal and will receive updates. You don't need to do anything.
Users who were previously using the tdarr container will need to set up the container again and restore from a backup. There is now no need for a separate MongoDB container. Please see the following for help:
http://tdarr.io/tools
https://github.com/HaveAGitGat/Tdarr/wiki/2---Installation
Tdarr: added volumes with the same paths as sonarr/radarr to allow the use of plex autoscan with …
> Tdarr changes

- appveyor.yml
- community.yml
- roles/calibre/tasks/main.yml
A much better Calibre role than the current Calibre-RDP one, plus this docker source is maintained.   Unlike the other submitted LSIO role, this one puts books in the standard /mnt/local/Media/Books directory.
> Add LSIO Calibre Role 

- roles/jellyfin/tasks/main.yml
Updated role to remove /mnt/strm path being mapped. This can be accessed via the /mnt path that is already added.
> Jellyfin: Updated Role

- roles/beets/tasks/main.yml
- roles/plex2/defaults/main.yml
The flags -it for a docker exec command running via cron aren't needed and in fact error out with "The input device is not a TTY".
> Remove -it flags from cron job

- roles/plex2/defaults/main.yml
- roles/transmissionvpn/tasks/main.yml
Necessary for Transmission to open port on load.
> Add DNS Server to Transmission VPN Docker

- README.md
- appveyor.yml
- community.yml
- roles/mylar3/tasks/main.yml
Mylar3 is the port of mylar (comics downloader) to phyton 3. Developement has stopped on mylar and is now set on mylar3.
I changed the TZ from the original mylar main.yml mounting /etc/timezone as volume, since the original own in mylar was not working.
> Add role: mylar3 (v3 for mylar)

- roles/sonarrx/tasks/template.yml
`phantom` tag deprecated in favor of `nightly` tag
> SonarrX: Update Docker image tag

- roles/requestrr/tasks/main.yml
Prevents joining the bridge network.
Changed misspelled network alias.
> Requestrr - added purge_networks

- roles/delugevpn/tasks/main.yml
Docker image has now been updated to support PIA NextGen.
https://github.com/binhex/arch-delugevpn/issues/197#issuecomment-700652539
Updated the download link for OpenVPN configurations to the next gen link. ZIP structure is the same as before and in my environment this appears to work as a slot in replacement.
Theoretically the same applies to binhex's other VPN containers but I don't run any of the others, if people would like to test.
> DelugeVPN: Update OpenVPN configuration to PIA NextGen

- roles/watchtower/tasks/main.yml
- roles/watchtower/templates/watchtower.env.j2
Use pre-populated ENV file for configuration. Allows for user edits in the env file and re-running the role to re-deploy with persistent configuration.
This should be replaced with the variable-based approach when implemented on Community.
> Watchtower: Add ENV file configuration

- roles/transmissionvpn/tasks/main.yml
`:latest-alpine` deprecated, `:latest` now based on Alpine per dev.
> TransmissionVPN: Fix Docker tag

- roles/transmissionx/tasks/main.yml
- roles/transmissionx/tasks/settings/dynamic.yml
- roles/transmissionx/tasks/settings/main.yml
- roles/transmissionx/tasks/settings/static.yml
- roles/transmissionx/tasks/template.yml
transmissionx did not have any published ports until now, because of this the client was not "connectable" from torrent trackers.
This creates a different published ports for each instance (starts from 51413 and adds 1 each time).
I've also fixed a bit of the "header" grafic and added credits to saltydk for his work on https://github.com/Cloudbox/Community/pull/273
I've tested on my already deployed role, with a total 5 instances of transmission
> Added published ports for transmissionx role

- roles/mylar3/subtasks/hotio_migration.yml
- roles/mylar3/tasks/main.yml
Change `mylar3` image to `hotio/mylar3` and add migrator for config path changes
Tested clean deploy as well as migration with latest `develop`
- [n/a] I have added my new role to `appveyor.yml`
- [n/a] I have added my new role to `community.yml`
- [n/a] I have made corresponding changes to the documentation
Fixes #256
> Mylar3: Switch to hotio image and add migrator

- roles/tdarr/tasks/main.yml
On Sunday 31st Jan, this container (tdarr:latest) will be replaced with Tdarr v2. To keep using this exact container, use tag 1.3003.
If you're coming from V1, unfortunately V2 uses a new database and there have been a lot of changes so you'll need to start fresh.
More info: http://tdarr.io/docs/
The update to V2 will break old and new installs due to internal path changes in the container, making the current volume-mappings inadequate.  The server data (database, samples, plugins etc) is now stored in '/app/server'
V2 also uses an additional container for the actual processing of the workload (tdarr_node)
> Tdarr pinned to 1.3003 release

- roles/deemix/tasks/main.yml
Needs a proper mount for downloads. By default the app sends downloads to `/downloads` which points to something like `/var/lib/docker/volumes/f2c8324c2aaffb5d81a0f6ea70110cb180d96caa6be1c6f5941d4577cf71d4f9/_data` inside the container.
> Override the default downloads mount with a Cloudbox path

- README.md
- appveyor.yml
- community.yml
- roles/changedetection/tasks/main.yml
Self-hosted change monitoring of web pages.
Added Changedetection.io service.
https://github.com/dgtlmoon/changedetection.io
Tested on fresh cb installation, Ubuntu 18.04 server, online and offline multiple times.
> Added Changedetection.io service

- roles/filebot/tasks/main.yml
Since filebot can modify the systems files, this should not be exposed as it currently is. This should be password protected as the other applications are. 
> fix: adding create htpasswd to filebot

- README.md
- appveyor.yml
- community.yml
- roles/smokeping/tasks/main.yml
Smokeping keeps track of your network latency.
- Basics are, edit the Targets file located in /opt/smokeping/config/Targets to ping the hosts you're interested in to match the format found there.
- Reboot container.
https://hub.docker.com/r/linuxserver/smokeping
> Adding SmokePing service

- appveyor.yml
- community.yml
- roles/firefly/tasks/main.yml
Firefly III service added as role.
Adding Firefly III to the community repo. Firefly III is a free and open source personal finance manager.
More about it here.
> Adding Firefly III service

- appveyor.yml
- community.yml
- defaults/settings.yml.default
- roles/easycountdown/tasks/main.yml
Easy countdown is an easy to setup countdown page. Can be setup as a countdown or as a timer
https://github.com/Yooooomi/easy-countdown
> Easy Countdown (Static countdown page)

- defaults/settings.yml.default
- roles/moviematch/tasks/main.yml
Simple change due to an issue with moviematch in which local domains is the solution. Seems best to make it user variable as well.
> Moviematch: Change plex url to user variable. Set to local domain by default

- roles/moviematch/tasks/main.yml
Was having an issue, documented here: https://github.com/Cloudbox/Community/issues/369
The Role was using "LIBRARY_TITLE_FILTER", which is a v2 variable. - https://github.com/LukeChannings/moviematch/blob/main/README.markdown#Configuration
Should have been using "LIBRARY_FILTER" variable as the latest stable is v.1.10 which has different variables. - https://github.com/LukeChannings/moviematch/tree/v1#configuration
Modified the role's `main.yml` file with the aforementioned edit and ran the role, this time it loaded all the specified libraries from the `community/settings.yml` file.
New debug output shows:
```
DEBUG Log level DEBUG
DEBUG getSections: http://plex:32400/library/sections
INFO Listening on port 8000
DEBUG Available libraries: Kids Movies, Movies, Stand-up Comedy, Anime, Kids …
```
> Update main.yml for MovieMatch Role

- roles/bitwarden/tasks/main.yml
Bitwardenrs project name was changed to vaultwarden, including the docker image.  
See https://github.com/dani-garcia/vaultwarden/discussions/1642 for discussion of the change.
Will update the wiki once the pull request is merged.
Changed docker image to vaultwarden. Ran role. Confirmed bitwarden functioned as expected.
> Changed docker image to vaultwarden

- roles/prowlarr/defaults/main.yml
Change Prowlarr image tag from `nightly` to `testing` to get pre-release builds instead of every commit
> Prowlarr: Change to `testing` tag

- roles/sonarrx/tasks/template.yml
Since sonarr v3 is now stable i propose changing the image to release.
Was already done in Cloudbox/Cloudbox see https://github.com/Cloudbox/Cloudbox/commit/d2416b8f032fbee59b2457b796b1c2d2b41f818f
This is a simple change, I tested it on my Cloudbox installation
> sonarrx: change image to release

- .github/workflows/ci.yml
- README.md
- community.yml
- roles/readarr/tasks/main.yml
Added Readarr role using 'hotio/readarr' container.
Currently there is only 'nightly' images, no 'latest' as in BETA, however functionality is good.
Once a 'latest' tag is available will edit role.
Also, "Media/Books" is passed along as "/library" in order to work well with the 'Calibre' role when using it's server function, allowing Calibre to manage media provided by Readarr.
Used to build eBook library alongside Jackett/NZBHydra2 with DelugeVPN/NZBget.
Content passed to 'Calibre', and can also be browsed and downloaded via 'Calibre-web' to eReaders.
- [✓] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [✓] I have updated the header in any files I may have used as templates with my own information
- [✓] I have added my new role …
> Adding Readarr role via hotio/readarr container, and light cleanup of README

- roles/transmissionvpn/tasks/main.yml
The transmissionvpn docker image assumes that you have mounted a volume to /data, and sets a lot of defaults based on that, such as the default download dir, incomplete downloads dir, and watch dir. 
When I installed transmissionvpn this data volume was not configured. This meant that docker generated the volume automatically and transmission used that dir rather than downloading to the created torrents folders.
I added a mount point pointing `data` (in the container) to `{{ downloads.torrents }}/transmissionvpn` (on the disk).
Ran it locally and verified in portainer that it was being mounted correctly:  
I wasn't sure how to test it in the case that `torrents_download_path` doesn't exist and would appreciate any input you have on whether my code looks correct
> Add a "data" directory since transmissionvpn expects it

- roles/minecraft/tasks/main.yml
The config bind makes the community role not work properly. Removing it fixes it. This is because of a change in the docker image and the role just hasnt been adjusted yet. 
I deleted the bind, created a Server and did basic functionality testing. Everything seemed to work properly
> removed the "config" bind

- roles/overseerr/tasks/main.yml
- roles/overseerrx/tasks/template.yml
For some reason, with many DNS providers, TMDB resolves to 127.0.0.1, which completely breaks Overseerr. Using Cloudflare DNS, this happens as well. The Google DNS servers still seem to resolve it fine though. This patch forces the Overseerr container to use Google DNS and thereby fixing this issue for many users, including myself.
I understand that this might not get merged as this is somewhat of a hotfix/workaround which is not required for everybody running this. From what I hear, it mostly affects users running this on Hetzner servers. However, this seems like a cleaner way to fix this issue than having to change the DNS servers for my entire server.
> fix(overseerr): force container to use Google DNS to fix TMDB API issues.

- community.yml
- roles/whisparr/tasks/main.yml
Whisparr is an adult movie collection manager for Usenet and BitTorrent users.
> add Whisparr

- README.md
- community.yml
- defaults/settings.yml.default
- roles/tdarrv2-node/tasks/main.yml
- roles/tdarrv2/tasks/main.yml
- Added tdarrv2 web gui role
- Added tdarrv2 node role
- Updated readme to added tdarrv2. Need to set transcode cache directory
and possibly some other things to still make it work.
- Added settings in case you wanted to set subdomain to tdarr instead of
the default tdarrv2
- The tag to install is tdarrv2, which will install both roles. Could
change this later maybe if people wanted to spin up multiple nodes.
- This will automatically add the node to the web interface to use
Please review this template and edit it as appropriate.  It's not been provided as a thing to ignore.  If there are things that don't apply, remove them.  Don't just check boxes for the sake of checking boxes.  Remove this paragraph and the related thing below.
Updated tdarr from v1 to tdarrv2 and make it work
Please …
> Add tdarrv2 role

- roles/btrfsmaintenance/tasks/main.yml
By default, the BTRFS_BALANCE_MOUNTPOINTS and BTRFS_SCRUB_MOUNTPOINTS are set to `/` so the role won't have any effect on a system with just `/opt` as btrfs. By setting the mount points to 'auto', the role will work with btrfs partitions other than `/`.
Tested the same changes on Saltbox. Adding here because this is where the role originated. FWIW, I was the person that first brought up btrfsmaintenance in the CB Discord.
> Set balance and scrub mountpoints to 'auto'

- roles/calibre/tasks/main.yml
Please review this template and edit it as appropriate.  It's not been provided as a thing to ignore.  If there are things that don't apply, remove them.  Don't just check boxes for the sake of checking boxes.  Remove this paragraph and the related thing below.
Calibre does not boot without this extra parameter. This is explicity provided on calibre's readme
With and without this paramater for comparison.
> Update Calibre role w/ security_opts
